WebUI/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entities;
using Domain.Abstract;
using WebUI.Infrastructure;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class PersonController : Controller
    {
        private IPersonRepository repository;

        public PersonController(IPersonRepository repo)
        {
            repository = repo;
        }
        public ViewResult ShortInfo()
        {
            PersonViewModel infoPerson = null;
            try
            {
                string id = Session.SessionID;
            
            if (Session[Session.SessionID] != null)
                {
                infoPerson = new PersonViewModel() { Bar=new List<StringHelper>()};
                    infoPerson.Person = (Person)Session[Session.SessionID]; 
                    infoPerson.Bar.Add(new StringHelper() { Link = "Задания "+repository.CountNewTask(SessionManager.GetPerson()), 
                        Action = "List", Controller = "Task" });
                    infoPerson.Bar.Add(new StringHelper() { Link = "Сообщения "+repository.CountNewMessage(SessionManager.GetPerson()), 
                        Action = "List", Controller = "Message" });
                    if (SessionManager.CheckUserIsInRole("Admin"))
                        infoPerson.Bar.Add(new StringHelper() { Link = "Пользователи", 
                            Action = "List", Controller = "Admin" });
                }
            }
            catch { }
            return View(infoPerson);
        }
        public ViewResult AdminBar()
        {
            if (SessionManager.CheckUserIsInRole("Admin"))
                return View(true);
            else
                return View(false);
        }
        public ViewResult Profile()
        {
            return View(SessionManager.GetPerson());
        }
    }
}

WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
</head>

<body>
    <div id="header">
        <div class ="title">Менеджер заданий</div>
    </div>
   <div id="content">
   @if (TempData["message"] != null)
        {
            <div class="Message">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" 
        type="text/javascript"></script>
</head>

<body>
    <div id="header">
        @{Html.RenderAction("ShortInfo", "Person");}
        <div class ="title">Менеджер заданий</div>
    </div>
   <div id="content">
   @if (TempData["message"] != null)
        {
            <div class="Message">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>