WebUI/Models/TaskViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entities;

namespace WebUI.Models
{
    public class TaskViewModel
    {
        public IQueryable<Task> Tasks { get; set; }
        public IEnumerable<string> Categorize { get; set; }
        public bool isManager { get; set; }
    }
}

WebUI/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;
using WebUI.Models;
using WebUI.Infrastructure;

namespace WebUI.Controllers
{
    
    public class TaskController : Controller
    {
        private ITaskRepository repository;
        private IPersonRepository personRepository;

        public TaskController(ITaskRepository repo,IPersonRepository personRepo)
        {
            repository = repo;
            personRepository = personRepo;
        }
        [SharweAuthorize(Roles = "User")]
        public ViewResult WatchTask(int taskId=0)
        {
            bool isWorker = (repository.Tasks.First(x => x.TaskID == taskId).ToID ==
                ((Person)Session[Session.SessionID]).PersonID) ? true : false;
            Task task = repository.Tasks.First(x=>x.TaskID==taskId);
            if ((task.StatusID == 1) && (isWorker)) { repository.ChangeStatus(taskId); }
            return View(new TaskCommentModel(){Task=task,Comment = new Comment(),IsWorker=isWorker});
        }

        [HttpPost]
        public PartialViewResult WatchTask(int taskId,TaskCommentModel taskCommentodel)
        {
            if (ModelState.IsValid)
            {
                Comment tempComment = taskCommentodel.Comment;
                tempComment.ID = 0;
                tempComment.FromID = ((Person)System.Web.HttpContext.Current.Session[
                System.Web.HttpContext.Current.Session.SessionID]).PersonID;//эта зверюга возвращает ID пользователя                    
                tempComment.TaskID = taskId;
                repository.SaveComment(tempComment);
            }
            return PartialView("testPartial", repository.Tasks.First(x => x.TaskID == taskId).Comments.OrderBy(x=>x.When));
        }

        [HttpPost]
        public PartialViewResult Check(int taskId, TaskCommentModel taskCommentodel)
        {
            if (ModelState.IsValid)
            {
                InTask tempInTask = new InTask();
                tempInTask.CheckTask = taskCommentodel.newTask;
                tempInTask.TaskID = taskId;
                repository.SaveCheck(tempInTask);
            }
            return PartialView("taskPartial", repository.Tasks.First(x => x.TaskID == taskId).CheckList.OrderBy(x => x.ID));
        }

        public ViewResult List()
        {
            if (Session[Session.SessionID] != null)
            {
                TaskViewModel tvm = new TaskViewModel();
                Person currentPerson = (Person)Session[Session.SessionID];
                
                tvm.Tasks = repository.PersonTasks(currentPerson);

                tvm.isManager=currentPerson.InRoles("Manager");

                tvm.Categorize = new List<string>();
                //пока нет навигации заданий
                //tvm.Categorize = tvm.Tasks.GroupBy(x => x.From.Email)
                //    .Select(x=>x.FirstOrDefault())
                //    .Select(x=>x.From.FirstName)
                //    .OrderBy(p => p);
                
                return View(tvm);
            }
            else
                return View();
        }

        //создание задания
        [SharweAuthorize(Roles = "Manager")]
        public ViewResult Edit(int? taskId)
        {
            TaskEditModel task = new TaskEditModel() { Task = repository.Tasks
                .FirstOrDefault(p => p.TaskID == taskId),
                PersonLists=new List<SelectListItem>() };
            foreach (var p in personRepository.Persons)
                task.PersonLists.Add(new SelectListItem { Text = p.FirstName+" "+p.SecondName, Value = p.PersonID.ToString() });
            return View(task);
        }
        [SharweAuthorize(Roles = "Manager")]
        [HttpPost]
        public ActionResult Edit(Task task, int Toid = 0,string[] mas=null)//TaskEditModel task
        {
            if (ModelState.IsValid)
            {
                task.FromID = SessionManager.GetPerson().PersonID;
                task.ToID = Toid;
                int k = repository.SaveTask(task);
                foreach (var m in mas)
                    if (m!="")
                        repository.SaveCheck(new InTask { CheckTask = m, TaskID = k });
                TempData["message"] = string.Format("Task has been change");
                return RedirectToAction("List");
            }
            else
                return View(task);
        }
        [SharweAuthorize(Roles = "Manager")]
        public ViewResult Create()
        {
            TaskEditModel task = new TaskEditModel(){Task = new Task{TaskID=0 ,StatusID=1},
                PersonLists=new List<SelectListItem>()};
            foreach (var p in personRepository.Persons)
                task.PersonLists.Add(new SelectListItem { Text = p.FirstName, 
                    Value = p.PersonID.ToString() });
            return View("Edit", task);
        }
        [HttpPost]
        public ActionResult DeleteCheck(int checkId)
        {
            repository.DeleteCheck(checkId);
            return RedirectToAction("list");
        }
        [HttpPost]
        public ActionResult Done(int taskId)
        {
            repository.DoneTask(taskId);
            return RedirectToAction("list");
        }
        [HttpPost]
public ActionResult Checked(string isChecked)
{
    int id;
    if (int.TryParse(isChecked,out id))
    {
        repository.ChangeCheckBox(id);
    }
    return null;
}

    }
}

WebUI/Views/Task/Edit.cshtml
@model WebUI.Models.TaskEditModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Создать</h2>
    @using (Html.BeginForm("Edit", "Task",FormMethod.Post)){
    @Html.ValidationSummary()    
    <h3>Кому:</h3>
    @Html.DropDownListFor(x => x.ToId, Model.PersonLists)
    @Html.EditorFor(x => x.Task)
    <h3>список дел</h3>
    <div id="task" style="color: Black;">

    </div>
        <div id="parentId">
  <div>
  @Html.TextBoxFor(x => x.mas, "name[1]")
    <a style="color:green;" onclick="return addField()" href="#">[+]</a>
  </div>
</div>
    <input type="submit" value="Дать задание"/>   
    }
@Html.ActionLink("Cancel and return to List", "List")

<script type="text/javascript">
    var countOfFields = 1; // Текущее число полей
    var curFieldNameId = 1; // Уникальное значение для атрибута name
    var maxFieldLimit = 25; // Максимальное число возможных полей
    function deleteField(a) {
        if (countOfFields > 1) {
            // Получаем доступ к ДИВу, содержащему поле
            var contDiv = a.parentNode;
            // Удаляем этот ДИВ из DOM-дерева
            contDiv.parentNode.removeChild(contDiv);
            // Уменьшаем значение текущего числа полей
            countOfFields--;
        }
        // Возвращаем false, чтобы не было перехода по сслыке
        return false;
    }
    function addField() {
        // Проверяем, не достигло ли число полей максимума
        if (countOfFields >= maxFieldLimit) {
            alert("Число полей достигло своего максимума = " + maxFieldLimit);
            return false;
        }
        // Увеличиваем текущее значение числа полей
        countOfFields++;
        // Увеличиваем ID
        curFieldNameId++;
        // Создаем элемент ДИВ
        var div = document.createElement("div");
        // Добавляем HTML-контент с пом. свойства innerHTML
        //name[" + curFieldNameId + "]
        div.innerHTML = "<input id=\"mas\" name=\"mas\" type=\"text\" style=\"width:300px;\" /><a style=\"color:green;\" onclick=\"return addField()\" href=\"#\">[+]</a>";
        // Добавляем новый узел в конец списка полей
        document.getElementById("parentId").appendChild(div);
        // Возвращаем false, чтобы не было перехода по сслыке
        return false;
    }
</script>

WebUI/Views/Task/List.cshtml
@model WebUI.Models.TaskViewModel

@{
    ViewBag.Title = "Список заданий";
}

<h2>Список заданий</h2>
@if (Model != null)
{
    <div id="categories">
@foreach (var link in Model.Categorize)
{
    @Html.RouteLink(link, new
{
    controller = "Task",
    action = "List",
    taskId = link,
    page = 1
},
    new { @class = link == ViewBag.SelectedCategory ? "selected" : null }
    );
}
    </div>
    if (Model.isManager)
    {
    <p>@Html.ActionLink("Создать новую задачу", "Create")</p>
    }
  foreach (var p in Model.Tasks)
  {
    <div class="item">
    <h3>
    @Html.RouteLink(p.Title, new
{
    controller = "Task",
    action = "WatchTask",
    taskId = p.TaskID
})
    </h3>
    От: @p.From.FirstName<br/>
    Кому: @p.To.SecondName<br />
    Статус: @p.Status.InStatus<br />
    Название: @p.Text<br />
    <h5>Выдано: @p.Time</h5>
    Сделано @{int count=0; foreach (var c in p.CheckList) { if (c.IsChecked) { count++; } } @count ;} из @p.CheckList.Count части
    </div>
}
}

WebUI/Views/Task/WatchTask.cshtml
@model WebUI.Models.TaskCommentModel

@{
    ViewBag.Title = "Задание";
}
<h2>Задание</h2>

    Статус
    @Model.Task.Status.InStatus<br />
    Название
    @Model.Task.Title<br/>
    Текст задания
    @Model.Task.Text<br />
    @Model.Task.Time<br/>
    <div id="resulttask" style="color: Black;">
    @foreach (var chkl in Model.Task.CheckList)
    {
       @Html.CheckBox(chkl.ID.ToString(),chkl.IsChecked)@chkl.CheckTask
       using (Html.BeginForm("DeleteCheck", "Task"))
       {
                @Html.Hidden("CheckID", chkl.ID)
                <input type="submit" value="Удалить"/>
       }
        <br/>
    }
    
    </div>
    

    @if (Model.IsWorker)
    {
        <script type="text/javascript">
            $(function () {
                $(':checkbox').change(function () {
                    $.ajax({
                        url: '@Url.Action("Checked")',
                        type: 'POST',
                        data: { isChecked: $(this).attr("name") }, //isChecked: //is(':checked')
                        success: function (result) {

                        }
                    });
                });
            });
</script>

    }
    else
    {
        //принять задание
        using (Html.BeginForm("Done", "Task"))
       {
                @Html.Hidden("TaskID", Model.Task.TaskID)
                <input type="submit" value="Принять задание"/>
       }
        
        using (Ajax.BeginForm("Check", new
        {
            controller = "Task",
            action = "Check",
            taskId = Model.Task.TaskID
        },
    new AjaxOptions
    {
        HttpMethod = "POST",
        UpdateTargetId = "resulttask",
        OnBegin = "onBegin()",
        OnComplete = "onComplate()"
    }))
        {
    @Html.TextBoxFor(x => x.newTask)
    <input type="submit" value="Добавить" />
        }

    }
    <div id="result" style="color: Black;">
    @foreach (var c in Model.Task.Comments)
    {
         <hr/>
         @c.Text<br/>
         @c.From.FirstName<br/>
         @c.When<br/>
    }
    </div>


<script type="text/javascript">
    //Method that will be on begin of Ajax request, here we are displaying some text to user while update is    //going on
    function onBegin() {
        $('#loading').show();
    }

    //Method that will be called once ajax request was done and we will hide the loading text
    function onComplate() {
        $('#loading').hide();
    }

</script>

<div id="loading" style="display:none; font-size:large; font-weight:bold">....Updating....</div>

@using (Ajax.BeginForm("WatchTask", new
{
    controller = "Task",
    action = "WatchTask",
    taskId = Model.Task.TaskID
},
    new AjaxOptions
    {
        HttpMethod = "POST",
        UpdateTargetId = "result",
        OnBegin = "onBegin()",
        OnComplete = "onComplate()"
    }))
{
    @Html.EditorFor(x => x.Comment)
    <input type="submit" value="Добавить" />
}
@Html.ActionLink("Вернуться к списку задач", "List")
   

WebUI/Views/Task/taskPartial.cshtml
@model IEnumerable<Domain.Entities.InTask>
@{
    ViewBag.Title = "taskPartial";
}
@foreach (var chkl in Model)
    {
       @Html.CheckBox(chkl.ID.ToString())@chkl.CheckTask
       using (Html.BeginForm("DeleteCheck", "Task"))
       {
                @Html.Hidden("CheckID", chkl.ID)
                <input type="submit" value="Удалить"/>
       }<br/>
    }
    @*разнести чеки, комменты и задание общее в разные контролы!*@

WebUI/Views/Task/testPartial.cshtml
@model IEnumerable<Domain.Entities.Comment>
@{
    ViewBag.Title = "testPartial";
}

@foreach (var c in Model)
    {
        <hr/>
         @c.Text<br/>
         @c.From.FirstName<br/>
         @c.When<br/>
    }